name: Label Manager

on:
  push:
    paths:
      - '.github/config/labels.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Synchronize labels
        uses: julb/action-manage-label@6ab8797f08ad692a9c1983de9b7c70fecaa927cf # v1
        with:
          from: .github/config/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
